// Bundled sample datasets (served from /public/samples, generated by
// backend/scripts/generate_sample_datasets.py) plus curated starter
// instructions shown in Sage without spending an LLM call.

export type SampleDataset = {
  id: string;
  name: string;
  file: string; // path under /public
  uploadName: string; // filename recorded on upload
  description: string;
  suggestions: string[];
};

export const SAMPLE_DATASETS: SampleDataset[] = [
  {
    id: "sales",
    name: "Sales Data",
    file: "/samples/sales.csv",
    uploadName: "sample_sales.csv",
    description: "1,000 rows of product sales with revenue, dates, and regions",
    suggestions: [
      "Show total revenue by region",
      "Which 5 products have the highest revenue?",
      "Remove rows with missing region",
    ],
  },
  {
    id: "employees",
    name: "Employee Data",
    file: "/samples/employees.csv",
    uploadName: "sample_employees.csv",
    description: "500 employees with departments, salaries, and hire dates",
    suggestions: [
      "Average salary by department",
      "Show the 10 highest paid employees",
      "How many employees were hired each year?",
    ],
  },
  {
    id: "survey",
    name: "Survey Results",
    file: "/samples/survey.csv",
    uploadName: "sample_survey.csv",
    description: "200 survey responses with ratings and demographics",
    suggestions: [
      "Show average rating by age group",
      "Count responses by gender",
      "Keep only ratings of 4 and above",
    ],
  },
];
